const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000);
const OPENAI_KEY=process.env.OPENAI_API_KEY||'', OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6';
const VOICE_PROVIDER=process.env.VOICE_PROVIDER||'elevenlabs', VOICE_KEY=process.env.VOICE_API_KEY||process.env.ELEVENLABS_API_KEY||'', VOICE_ID=process.env.VOICE_ID||process.env.ELEVENLABS_VOICE_ID||'';
const LA_KEY=process.env.LIVEAVATAR_API_KEY||'', LA_AVATAR=process.env.LIVEAVATAR_AVATAR_ID||'', LA_SANDBOX=String(process.env.LIVEAVATAR_IS_SANDBOX||'false').toLowerCase()==='true';
const TKEY=process.env.TIKTOK_CLIENT_KEY||'', TSECRET=process.env.TIKTOK_CLIENT_SECRET||'', TREDIRECT=process.env.TIKTOK_REDIRECT_URI||'', TSCOPES=(process.env.TIKTOK_SCOPES||'user.info.basic').split(/[ ,]+/).filter(Boolean).join(',');
const sessions=new Map(), histories=new Map(), queues=new Map(), liveClients=new Set();
const json=(r,s,b)=>{r.writeHead(s,{'Content-Type':'application/json'});r.end(JSON.stringify(b))};
const text=(r,s,b)=>{r.writeHead(s,{'Content-Type':'text/plain; charset=utf-8'});r.end(b)};
const body=async req=>{let b='';for await(const c of req)b+=c;try{return JSON.parse(b||'{}')}catch{return null}};
const aiInstructions='You are SARA, a warm Pakistani female AI virtual host. You are an AI, never claim to be human. Understand Urdu, Roman Urdu, Punjabi and Pakistani English. Reply in natural Urdu/Roman Urdu suitable for speaking aloud. Keep replies conversational, usually 1-3 short sentences. Never invent TikTok events, gifts, battles or viewer data.';
async function askAI(history){if(!OPENAI_KEY)throw Error('OPENAI_API_KEY is missing');const rr=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+OPENAI_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_MODEL,instructions:aiInstructions,input:history.slice(-12),max_output_tokens:220})});const d=await rr.json();if(!rr.ok)throw Error(d.error?.message||'OpenAI request failed');return String(d.output_text||'').trim()}
async function voice(t){if(!VOICE_KEY||!VOICE_ID)return null;if(VOICE_PROVIDER!=='elevenlabs')return null;const rr=await fetch('https://api.elevenlabs.io/v1/text-to-speech/'+encodeURIComponent(VOICE_ID)+'?output_format=pcm_24000',{method:'POST',headers:{'xi-api-key':VOICE_KEY,'Content-Type':'application/json','Accept':'audio/pcm'},body:JSON.stringify({text:t,model_id:'eleven_v3',language_code:'ur',voice_settings:{stability:.48,similarity_boost:.8,speed:.98}})});if(!rr.ok)throw Error('ElevenLabs request failed ('+rr.status+')');return{audioBase64:Buffer.from(await rr.arrayBuffer()).toString('base64'),format:'pcm_24000'}}
async function liveToken(){if(!LA_KEY||!LA_AVATAR)throw Error('LiveAvatar is not configured');const rr=await fetch('https://api.liveavatar.com/v1/sessions/token',{method:'POST',headers:{'X-API-KEY':LA_KEY,'Content-Type':'application/json'},body:JSON.stringify({mode:'LITE',avatar_id:LA_AVATAR,is_sandbox:LA_SANDBOX})});const d=await rr.json();if(!rr.ok)throw Error(d?.data?.message||d?.error?.message||'LiveAvatar token failed');return{session_token:d.data?.session_token,session_id:d.data?.session_id||null,avatar_id:LA_AVATAR,sandbox:LA_SANDBOX}}
function sid(req,res){const m=(req.headers.cookie||'').match(/(?:^|; )ai_sid=([^;]+)/);if(m)return m[1];const id=crypto.randomBytes(24).toString('hex');res.setHeader('Set-Cookie','ai_sid='+id+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400');return id}
async function message(req,res){const id=sid(req,res),x=await body(req);const input=String(x?.text||'').trim().slice(0,1200);if(!input)return json(res,400,{error:'text required'});if(!OPENAI_KEY)return json(res,503,{error:'AI not configured. Add OPENAI_API_KEY.'});const h=histories.get(id)||[];h.push({role:'user',content:input});try{const reply=await askAI(h);h.push({role:'assistant',content:reply});histories.set(id,h.slice(-12));const v=await voice(reply);return json(res,200,{ok:true,reply,...(v||{})})}catch(e){return json(res,502,{error:e.message})}}
function tiktokRedirect(req){if(TREDIRECT)return TREDIRECT;const proto=String(req.headers['x-forwarded-proto']||'http').split(',')[0];return proto+'://'+req.headers.host+'/auth/tiktok/callback'}
function oauthState(){const n=crypto.randomBytes(24).toString('base64url'),s=crypto.createHmac('sha256',TSECRET).update(n).digest('base64url');return n+'.'+s}
function validState(st,c){if(!st||!c||!TSECRET)return false;const [n,s]=String(st).split('.');const e=crypto.createHmac('sha256',TSECRET).update(n||'').digest('base64url');return n===c&&s===e}
const server=http.createServer(async(req,res)=>{
 const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/api/health')return json(res,200,{ok:true,aiConfigured:!!OPENAI_KEY,voiceConfigured:!!(VOICE_KEY&&VOICE_ID),liveAvatarConfigured:!!(LA_KEY&&LA_AVATAR),liveAvatarAvatarConfigured:!!LA_AVATAR,tiktokOAuthConfigured:!!(TKEY&&TSECRET),tiktokRedirectUri:tiktokRedirect(req)});
 if(u.pathname==='/api/sara/message'&&req.method==='POST')return message(req,res);
 if(u.pathname==='/api/liveavatar/token'&&req.method==='POST'){try{return json(res,200,{ok:true,...await liveToken()})}catch(e){return json(res,503,{error:e.message})}}
 if(u.pathname==='/api/voice'&&req.method==='POST'){const x=await body(req);try{const v=await voice(String(x?.text||'').slice(0,1200));return json(res,200,{ok:true,...(v||{})})}catch(e){return json(res,502,{error:e.message})}}
 if(u.pathname==='/api/sara/control'&&req.method==='POST')return json(res,200,{ok:true,action:(await body(req))?.action||'resume'});
 if(u.pathname==='/auth/tiktok'){if(!TKEY||!TSECRET)return text(res,503,'TikTok credentials are not configured');const st=oauthState();res.setHeader('Set-Cookie','tt_state='+encodeURIComponent(st.split('.')[0])+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=600');const q=new URLSearchParams({client_key:TKEY,response_type:'code',scope:TSCOPES,redirect_uri:tiktokRedirect(req),state:st});res.writeHead(302,{Location:'https://www.tiktok.com/v2/auth/authorize/?'+q});return res.end()}
 if(u.pathname==='/auth/tiktok/callback'){const code=u.searchParams.get('code'),st=u.searchParams.get('state'),c=(req.headers.cookie||'').match(/(?:^|; )tt_state=([^;]+)/)?.[1];if(!code||!validState(st,decodeURIComponent(c||'')))return text(res,400,'TikTok authorization state is invalid or expired');try{const form=new URLSearchParams({client_key:TKEY,client_secret:TSECRET,code,grant_type:'authorization_code',redirect_uri:tiktokRedirect(req)});const rr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});const d=await rr.json();if(!rr.ok||d.error)throw Error(d.error_description||d.error||'Token exchange failed');const id=crypto.randomBytes(32).toString('hex');sessions.set(id,{tiktok:d,created:Date.now()});res.setHeader('Set-Cookie','sid='+id+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800');res.writeHead(302,{Location:'/'});return res.end()}catch(e){return text(res,502,'TikTok connection failed: '+e.message)}}
 if(u.pathname==='/api/me')return json(res,200,{authenticated:[...sessions.values()].length>0});
 if(u.pathname==='/'||u.pathname==='/index.html')return res.end(fs.readFileSync(path.join(__dirname,'public','index.html')));
 if(u.pathname==='/runtime.js')return res.end(fs.readFileSync(path.join(__dirname,'runtime.js')));
 return text(res,404,'Not found');
});
server.listen(PORT,()=>console.log('SARA AI listening on '+PORT));
